# Generated by Django 5.1 on 2024-09-02 18:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_message_chat'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='person_a',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='person_a_chat_set', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chat',
            name='person_b',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='person_b_chat_set', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
