# Generated by Django 5.1 on 2024-09-02 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chat_person_a_chat_person_b'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='person_a',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='person_b',
        ),
    ]
