# Generated by Django 5.1 on 2024-09-04 20:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_alter_chat_members'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='members',
            field=models.ManyToManyField(blank=True, default=None, related_name='person_b_chat_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
